### ISSUE TITLE
Parity Gas Accounting

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/fvm-specs#20]
Looking at substrate, it seems like they're doing gas accounting by instrumentation: https://github.com/paritytech/wasm-utils. This would allow using VMs that don't have native gas accounting support, and may be more performant.

Their logic will also perform stack height checks, etc. So we'll likely want to use it anyways.

**Comment by Stebalien** [comment]
Hm. So, it looks like wasmer's way of doing this is what I was originally proposing: they _do_ instrument code to modify a global. So no, we probably don't want to use parity or near's method.

Note: near is going with the "globals" method, but they're not using wasmer to avoid depending on it too heavily. I don't hold a strong opinion there as long as we can _spec_ the behavior.

**Comment by raulk** [comment]
We initially adopted wasmtime's instrumentation. But when performing the data analysis to parametrize [FIP-0032](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0032.md), we noticed that memory instructions have wild variability. We decided to fork Parity's Wasm instrumentation into https://github.com/filecoin-project/fvm-wasm-instrument. This allows us to define our own gas costs per instruction, and provides better control and determinism on halt due to extraordinary conditions (e.g. out of stack).
